from . import paths
YOLO_CLASS_TO_VI = {
    "atiso": "Atiso",
    "bi_ngo": "Bí ngô",
    "bi_ngoi": "Bí ngòi",
    "bong_cai_trang": "Bông cải trắng",
    "bong_cai_xanh": "Bông cải xanh",
    "ca": "Cá",
    "ca_chua": "Cà chua",
    "ca_com": "Cá cơm",
    "ca_rot": "Cà rốt",
    "ca_tim": "Cà tím",
    "cai_bap": "Bắp cải",
    "can_tay": "Cần tây",
    "chanh_ta": "Chanh ta",
    "chanh_vang": "Chanh vàng",
    "chuoi_chin": "Chuối chín",
    "chuoi_xanh": "Chuối xanh",
    "cu_den": "Củ dền",
    "cu_gung": "Củ gừng",
    "cu_toi": "Củ tỏi",
    "dau_an": "Dầu ăn",
    "dau_bap": "Đậu bắp",
    "dau_phu": "Đậu phụ",
    "dau_tam": "Dâu tằm",
    "dau_tay": "Dâu tây",
    "dua_chuot": "Dưa chuột",
    "gao": "Gạo",
    "hanh_la": "Hành lá",
    "hanh_tay": "Hành tây",
    "hanh_tim": "Hành tím",
    "khoai_tay": "Khoai tây",
    "long_pepper": "Tiêu lốt", # Hoặc bạn có thể đổi thành "Hạt tiêu" nếu muốn chung chung
    "mat_ong": "Mật ong",
    "mui_tay": "Mùi tây",
    "nam_mo": "Nấm mỡ",
    "ot": "Ớt",
    "ot_chuong": "Ớt chuông",
    "ot_xanh": "Ớt xanh",
    "phuc_bon_tu": "Phúc bồn tử",
    "qua_bo": "Quả bơ",
    "qua_cam": "Quả cam",
    "qua_cherry": "Quả cherry",
    "qua_du_du": "Quả đu đủ",
    "qua_dua": "Quả dứa", # Có thể là Quả dừa tùy hình ảnh bạn train
    "qua_lac": "Hạt lạc", 
    "qua_le": "Quả lê",
    "qua_na": "Quả na",
    "qua_oi": "Quả ổi",
    "qua_ot": "Quả ớt", # Trong list có cả "ot" và "qua_ot", code set() sẽ lọc trùng cho bạn
    "qua_quat": "Quả quất",
    "qua_tao": "Quả táo",
    "qua_thanh_long": "Quả thanh long",
    "qua_trung": "Quả trứng",
    "qua_xoai": "Quả xoài",
    "rau_mui_ta": "Rau mùi ta",
    "sua_chua": "Sữa chua",
    "sua_tuoi": "Sữa tươi",
    "thit_bo": "Thịt bò",
    "thit_cuu": "Thịt cừu",
    "thit_ga": "Thịt gà",
    "thit_lon": "Thịt lợn",
    "toi_tay": "Tỏi tây",
    "tom": "Tôm",
    "uc_ga": "Ức gà",
    "viet_quat": "Việt quất",
    "xa_lach": "Xà lách"
}