from . import paths

YOLO_CLASS_TO_VI = {
    "bap_cai": "bắp cải",
    "bi_ngo": "bí ngô",
    "bong_cai_xanh": "bông cải xanh",
    "ca_chua": "cà chua",
    "ca_rot": "cà rốt",
    "cai_bap": "cải bắp",
    "cauliflower": "súp lơ",
    "chanh": "chanh",
    "chickpeas": "đậu gà",
    "dau": "đậu",
    "dau_tay": "dâu tây",
    "dua_chuot": "dưa chuột",
    "gao": "gạo",
    "gung": "gừng",
    "hanh_tay": "hành tây",
    "khoai_tay": "khoai tây",
    "lettuce": "xà lách",
    "mutton": "thịt cừu",
    "okra": "đậu bắp",
    "ot_chuong": "ớt chuông",
    "palm fruit": "trái cọ",
    "papaya": "đu đủ",
    "parsley": "ngò tây",
    "pear": "lê",
    "pitaya": "thanh long",
    "qua_bo": "bơ",
    "qua_cam": "cam",
    "qua_cherry": "cherry",
    "qua_chuoi": "chuối",
    "qua_dua": "dừa",
    "qua_tao": "táo",
    "qua_trung": "trứng",
    "radish": "củ cải",
    "raspberry": "mâm xôi",
    "red meat": "thịt đỏ",
    "small_pepper": "ớt nhỏ",
    "spring_onion": "hành lá",
    "thit_bo": "thịt bò",
    "thit_ca": "thịt cá",
    "thit_ga": "thịt gà",
    "thit_heo": "thịt heo",
    "toi": "tỏi",
    "tom": "tôm",
    "turmeric": "nghệ",
    "white beans": "đậu trắng",
    "white button mushroom": "nấm mỡ",
    "xoai": "xoài",
    "zucchini": "bí ngòi",
}